# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GitFlowExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GitFlowExample

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  target 'GitFlowExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'GitFlowExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for GitFlowExample-tvOS

  target 'GitFlowExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
